
version: '3.8'
# docker-compose -f docker-compose.dev.yml up
# docker-compose -f docker-compose.dev.yml config
services:
  client:
    image: client
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
      args:
        - REACT_APP_EMAILJS_SERVICE_ID
        - REACT_APP_EMAILJS_TEMPLATE_ID=${REACT_APP_EMAILJS_TEMPLATE_ID}
        - REACT_APP_EMAILJS_USER_ID=${REACT_APP_EMAILJS_USER_ID}
    volumes:
      - ./client/:/usr/src/app
    ports:
      - 3000:3000
  server:
    image: server
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    env_file:
      - ./.env
    environment:
      - PORT=5000
      - DOC_ID
      - CLIENT_EMAIL
      - PRIVATE_KEY