
version: '3.8'
# docker-compose -f docker-compose.dev.yml --env-file ./.env up
# docker-compose -f docker-compose.dev.yml --env-file ./server/.env config
services:
  server:
    image: server
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DOC_ID=${DOC_ID}
      - CLIENT_EMAIL=${CLIENT_EMAIL}
      - PRIVATE_KEY=${PRIVATE_KEY}