### GET all sheet data
GET http://localhost:5000/api/sheets

### GET dynamic sheet data
GET http://localhost:5000/api/sheets/draft

### GET dynamic sheet data
GET http://localhost:5000/api/sheets/static