name: Deployment Pipeline

on:
  push:
    branches:
      - main
      - '**'
    pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: npm install
        run: npm run install:all
      - name: lint
        run: npm run lint